[package]
name = "oxker-tui"
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
readme = "../README.md"
description = "A simple tui to view & control docker containers"
keywords = ["docker", "tui", "tokio", "terminal", "podman"]
categories = ["command-line-utilities"]

[[bin]]
name = "oxker"
path = "src/main.rs"

[dependencies]
oxker-core = { path = "../oxker-core" }
anyhow.workspace = true
async-trait = "0.1"
bollard.workspace = true
cansi.workspace = true
clap.workspace = true
crossterm.workspace = true
directories.workspace = true
futures-util.workspace = true
jiff.workspace = true
parking_lot.workspace = true
ratatui.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
uuid.workspace = true

[features]
exec_refactor = ["oxker-core/exec_refactor"]

[lints]
workspace = true

[dev-dependencies]
insta = "1.42.2"
criterion = { version = "0.5", features = ["html_reports"] }
dhat = "0.3"

[[bench]]
name = "ui_render_bench"
harness = false